### ISSUE TITLE
请问集成进wechat tweak以后如何使用呢？

### ISSUE THREAD

**Issue by com314159** [icpz/WeChat-AntiDuck#5]
使用的命令是什么？

**Comment by icpz** [comment]
使用这个安装即可 https://github.com/icpz/WeChatTweak-CLI
无需额外指令

**Comment by com314159** [comment]
我没有太理解，是wechat antiduck已经包含在wechatTweak cli里面了是吗？我安装了wechat tweak，启动了微信，但禁用音频闪避好像没成功。使用wechat tweak要怎么禁用音频闪避呢？

**Comment by com314159** [comment]
sudo wechattweak-cli install，已经成功了，看起来还需要执行一个启用的命令才能禁用音频闪避，能把具体的教程发一下吗？感谢感谢

**Comment by icpz** [comment]
cli 是个安装器，上面的地址是我 fork 的，我把里面的地址替换成了这个项目的 release，就是带有 antiduck 集成的 tweak。不需要额外命令启动，安装成功就会生效。

**Comment by icpz** [comment]
`wechattweak-cli version` 看一下是什么版本

**Comment by com314159** [comment]
上午的问题是安装成https://github.com/sunnyyoung/WeChatTweak-macOS了， 但安装https://github.com/icpz/WeChatTweak-CLI  后执行命令会报错

**Comment by com314159** [comment]
<img width="704" alt="image" src="https://github.com/icpz/WeChat-AntiDuck/assets/5378240/4cb68856-d1b8-4e91-8962-c7f7adb59a4f">

**Comment by icpz** [comment]
`sudo wechattweak-cli install`

**Comment by com314159** [comment]
我暂时使用原始的make 方法解决了。 [WeChat-AntiDuck](https://github.com/icpz/WeChat-AntiDuck)   sudo wechattweak-cli install  这个命令在M2  mac book pro 16寸的会报错，但sunnyyoung/WeChatTweak-macOS的不会报错，感觉是master落后太多了？

**Comment by com314159** [comment]
好像是多了--，算了，先make解决，感谢感谢

**Comment by icpz** [comment]
使用 makefile 安装的版本是不带有 wechat-tweak 集成的。

**Comment by com314159** [comment]
是的， 我只需要禁用音频闪避，微信语音的时候可以打游戏。其他功能不需要
