### ISSUE TITLE
mac m2 微信3.8.1好像无法inject 成功了

### ISSUE THREAD

**Issue by com314159** [icpz/WeChat-AntiDuck#6]
<img width="1009" alt="image" src="https://github.com/icpz/WeChat-AntiDuck/assets/5378240/76724f9e-56c4-4839-90f7-63f03411fafd">

**Comment by com314159** [comment]
今天刚更新的，然后就不行了

**Comment by icpz** [comment]
我本地没有复现，你是不是也更新过系统？如果是的话需要重新安装 xcode 或者 xcode-commandline-tools 
可以尝试用安装器安装： https://github.com/icpz/WeChatTweak-CLI/releases/tag/1.4i
安装方法： `sudo wechattweak-cli install`

**Comment by com314159** [comment]
对，也更新过系统

**Comment by com314159** [comment]
<img width="872" alt="image" src="https://github.com/icpz/WeChat-AntiDuck/assets/5378240/47ee8c62-b854-4380-820a-fb2f1c33a686">
还是不行，即使重装了xcode

**Comment by com314159** [comment]
![Uploading image.png…]()
这个也是不行的

**Comment by icpz** [comment]
请你重装 xcode cli tools 或者 xcode

**Comment by com314159** [comment]
算了， 不纠结了， 换成飞书了。 飞书没这个问题，不折腾这个微信了

**Comment by com314159** [comment]
> 请你重装 xcode cli tools 或者 xcode

这个我是rm -rf xcode cli tools 之后重装的，先不折腾了

**Comment by com314159** [comment]
如果有其他朋友遇到：1、 可以使用Wechat-AntiDuck   2、 也可以使用mac Loopback App 解决   3、 换其他应用，目前测试了飞书没这个问题。   我暂时长语音换飞书了。 或者zoom/腾讯会议，可以多试试，会议类的都应该可以解决。

**Comment by aur3l14no** [comment]
同遇到

**Comment by aur3l14no** [comment]
> 1、 可以使用Wechat-AntiDuck

是什么意思，不是不能用吗？
